const sections={dashboard:'Dashboard',settings:'Settings',fields:'Fields',sources:'Sources',brands:'Brands',models:'Models',rules:'Rules',profiles:'Profiles'};
let data={extension:{enabled:true,configVersion:1,minimumExtensionVersion:'1.0.0',updateIntervalMinutes:10},settings:{speed:500,alarmEnabled:true,autoRefresh:true,showPanel:true,showSuccessMessage:true,showErrorMessage:true,debugMode:false}};
const app=document.getElementById('app'); const title=document.getElementById('title');
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>render(b.dataset.section));
function toggleRow(label,key){return `<div class="row"><span>${label}</span><input type="checkbox" data-key="${key}" ${data.settings[key]?'checked':''}></div>`}
function render(section){title.textContent=sections[section];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===section));
 if(section==='dashboard')app.innerHTML=`<div class="card"><h3>Extension Status</h3><div class="row"><span>Status</span><span class="badge">${data.extension.enabled?'Enabled':'Disabled'}</span></div><div class="row"><span>Config Version</span><span>${data.extension.configVersion}</span></div><div class="row"><span>Update Interval</span><span>${data.extension.updateIntervalMinutes} minutes</span></div></div><div class="card"><h3>Architecture</h3><p class="muted">GitHub configuration → Firefox Extension → Acumatica. The extension will use local cache when the network is unavailable.</p></div>`;
 else if(section==='settings')app.innerHTML=`<div class="card"><div class="row"><span>Injection speed (ms)</span><input id="speed" type="number" min="100" step="100" value="${data.settings.speed}"></div>${toggleRow('Alarm','alarmEnabled')}${toggleRow('Auto refresh','autoRefresh')}${toggleRow('Show panel','showPanel')}${toggleRow('Success message','showSuccessMessage')}${toggleRow('Error message','showErrorMessage')}${toggleRow('Debug mode','debugMode')}</div>`;
 else app.innerHTML=`<div class="card"><h3>${sections[section]}</h3><p class="muted">This section is ready for the corresponding JSON editor. The JSON files in <code>../config/</code> are the source of truth.</p></div>`;
}
document.getElementById('save').onclick=()=>{const speed=document.getElementById('speed');if(speed)data.settings.speed=Number(speed.value);document.querySelectorAll('input[data-key]').forEach(x=>data.settings[x.dataset.key]=x.checked);data.extension.configVersion++;localStorage.setItem('acumatica-config-preview',JSON.stringify(data));document.getElementById('status').textContent='Saved locally — GitHub write-back not configured yet';render('settings')};
render('dashboard');
